# Generated by Django 3.2.3 on 2021-05-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('features', models.TextField(max_length=200)),
                ('inventory', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=140, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
