# Generated by Django 3.2.3 on 2021-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderid',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
